### ISSUE TITLE
RuntimeError: index 10 is of bounce for dimensions 0 with 5 (beam)

### ISSUE THREAD

**Issue by mdhasanai** [kenya-sk/show_attend_and_tell#1]
I got errors in 219 number line of model.py while validate.
please check your script again

**Comment by kenya-sk** [comment]
I tried to learn in 1epoch again in my environment, but there was no problem. Is the hyper parameter value default?

**Comment by mdhasanai** [comment]
Thanks for response. Yeh. I used default hyper parameters.
There was mistake in my vocabulary. I got solution..
Thanks you
